### ISSUE TITLE
Need a way to customize Service ports when we use Istio

### ISSUE THREAD

**Issue by rubel-ahammad** [inbucket/inbucket-community#40]
Istio decides protocol of a service port based on it's name or the value of the property named 'appProtocol'. Could you please add new property 'appProtocol' with value tcp for smtp and pop3 port?

For example, prefixing names with correct protocol works with Istio. (I just kept the names here
```
spec:
  ports:
    - name: http
      port: 9000
    - name: tcp-smtp
      port: 2500
    - name: tcp-pop3
      port: 1100
```

Could you please rename the port names as shown here? Or just let us override those using values files.
