### ISSUE TITLE
Wrong default value for PVC's accessMode.

### ISSUE THREAD

**Issue by Artebomba** [inbucket/inbucket-community#55]
Here in [pvc.yaml](https://github.com/inbucket/inbucket-community/blob/inbucket-2.5.0/helm-charts/inbucket/templates/pvc.yaml) spec.accessMode is set to {{ default .Values.persistence.accessMode "ReadWriteOnce" }} . 
Accordingly to the [Helm doc](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function) for the **default** func, the needed correct forms are:
 - {{ default  "ReadWriteOnce" .Values.persistence.accessMode }} 
 - {{ .Values.persistence.accessMode | default  "ReadWriteOnce" }}

The current value is incorrect because even if I specify 

```yaml
persistence:
  enabled: true
  path: /storage/inbucket
  size: 1059Mi
  className: manual-nfs
  accessMode: ReadWriteMany
```

the outcome still will be: 

```yaml
+ spec:
+   accessModes:
+     - ReadWriteOnce
```
because it always evaluetes "ReadWriteOnce" as a given value, not a default one. 

Also it would be great to add a possibility to specify "selectors" for PVs to match like:

```yaml
  selector:
    matchExpressions:
      - key: type
        operator: In
        values: [ "foo" ]
      - key: app
        operator: In
        values: [ "bar" ]
```
Documentations for PVC selectors https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
